This project is deprecated and unmaintained. Proceed with caution!

portpipe
========

[quote]
A tiny utility to pipe two separate ports together.

Usage
-----
[,bash]
----
portpipe: A tiny utility to pipe TCP requests to the server_port into
the client_port

SYNOPSIS
    portpipe [server_address:server_port] [client_address:client_port]
----

The `server_address` is the new server's address. You can usually leave it
blank. `server_port` is the port to serve from. `client_address` is the address
of the old server. The `client_port` is the port from the old server.

Example
-------
I have a https://github.com/ciarand/zen-srv[zen-srv] instance running on port
8080. If I run:

[,bash]
----
portpipe :6066 :8080
----

And in another tmux pane:

[,bash]
----
$ curl localhost:6066/zen
It's not fully shipped until it's fast
----

Or, if you'd like to use portpipe with another server:

[,bash]
----
$ portpipe :8088 google.com:80 &
[1] 59382
$ curl localhost:8088
2014/12/18 14:46:19 Beginning piping
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
----

License
-------
Copyright (c) 2014, Ciaran Downey <code@ciarand.me>

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

